grammar org.xtext.example.mydsl.MyDsl with org.eclipse.xtext.common.Terminals

generate myDsl "http://www.xtext.org/example/mydsl/MyDsl"

Model:
	commands+=Command*;

Path:
	name=STRING;

Array:
	(elements+=STRING)*;
	
	
Command:
	Create | Load | Print | Head;
	
Create:
	'CREATE'  path=Path ':' colums=Array;

Load:
	'LOAD' name=ID '=' path=Path ;
	
Print:
	'PRINT' name=ID ;

Head:
	'HEAD' name=ID ;


