/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.mydsl.generator;

import com.google.common.collect.Iterables;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.generator.AbstractGenerator;
import org.eclipse.xtext.generator.IFileSystemAccess2;
import org.eclipse.xtext.generator.IGeneratorContext;
import org.eclipse.xtext.xbase.lib.IteratorExtensions;
import org.xtext.example.mydsl.myDsl.Command;
import org.xtext.example.mydsl.myDsl.Create;
import org.xtext.example.mydsl.myDsl.Head;
import org.xtext.example.mydsl.myDsl.Load;
import org.xtext.example.mydsl.myDsl.Print;

/**
 * Generates code from your model files on save.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#code-generation
 */
@SuppressWarnings("all")
public class MyDslGenerator extends AbstractGenerator {
  @Override
  public void doGenerate(final Resource resource, final IFileSystemAccess2 fsa, final IGeneratorContext context) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("#generated_python_file");
    _builder.newLine();
    _builder.append("import pandas as pd");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.newLine();
    {
      Iterable<Command> _filter = Iterables.<Command>filter(IteratorExtensions.<EObject>toIterable(resource.getAllContents()), Command.class);
      for(final Command c : _filter) {
        CharSequence _compile = this.compile(c);
        _builder.append(_compile);
        _builder.newLineIfNotEmpty();
      }
    }
    _builder.append("\t\t\t");
    _builder.newLine();
    fsa.generateFile("file.py", _builder);
  }
  
  private CharSequence compile(final Command c) {
    CharSequence _switchResult = null;
    boolean _matched = false;
    String _name = c.eClass().getName();
    boolean _tripleEquals = (_name == "Create");
    if (_tripleEquals) {
      _matched=true;
      _switchResult = this.compile(((Create) c));
    }
    if (!_matched) {
      String _name_1 = c.eClass().getName();
      boolean _tripleEquals_1 = (_name_1 == "Load");
      if (_tripleEquals_1) {
        _matched=true;
        _switchResult = this.compile(((Load) c));
      }
    }
    if (!_matched) {
      String _name_2 = c.eClass().getName();
      boolean _tripleEquals_2 = (_name_2 == "Print");
      if (_tripleEquals_2) {
        _matched=true;
        _switchResult = this.compile(((Print) c));
      }
    }
    if (!_matched) {
      String _name_3 = c.eClass().getName();
      boolean _tripleEquals_3 = (_name_3 == "Head");
      if (_tripleEquals_3) {
        _matched=true;
        _switchResult = this.compile(((Head) c));
      }
    }
    if (!_matched) {
      _switchResult = "Error";
    }
    return _switchResult;
  }
  
  private CharSequence compile(final Print p) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("print(\"");
    String _name = p.getName();
    _builder.append(_name);
    _builder.append("\")");
    return _builder;
  }
  
  private CharSequence compile(final Load l) {
    StringConcatenation _builder = new StringConcatenation();
    String _name = l.getName();
    _builder.append(_name);
    _builder.append(" = pd.read_csv(\'");
    String _name_1 = l.getPath().getName();
    _builder.append(_name_1);
    _builder.append("\')");
    return _builder;
  }
  
  private CharSequence compile(final Create c) {
    StringConcatenation _builder = new StringConcatenation();
    String _name = c.getPath().getName();
    _builder.append(_name);
    _builder.append(" = pd.DataFrame([[\'Sacramento\', \'California\'], [\'Miami\', \'Florida\']], columns=[\'City\', \'State\'])");
    _builder.newLineIfNotEmpty();
    String _name_1 = c.getPath().getName();
    _builder.append(_name_1);
    _builder.append(".to_csv(\'");
    String _name_2 = c.getPath().getName();
    _builder.append(_name_2);
    _builder.append(".csv\', index=False)");
    _builder.newLineIfNotEmpty();
    return _builder;
  }
  
  private CharSequence compile(final Head l) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("print(");
    String _name = l.getName();
    _builder.append(_name);
    _builder.append(".head())");
    return _builder;
  }
}
